// <auto-generated />
using System;
using CrudApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CrudApi.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20220228165110_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrudApi.Models.Person", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<byte?>("Age")
                        .HasColumnType("smallint")
                        .HasColumnName("AGE");

                    b.Property<byte?>("HairColor")
                        .HasColumnType("smallint")
                        .HasColumnName("HAIR_COLOR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("NAME");

                    b.Property<bool?>("Sex")
                        .IsRequired()
                        .HasColumnType("boolean")
                        .HasColumnName("SEX");

                    b.HasKey("Id")
                        .HasName("ID");

                    b.ToTable("PERSONS");
                });
#pragma warning restore 612, 618
        }
    }
}
